server:
  port: 8081
spring:
  application:
    name: "RequestsCrediYaMicroservice"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "${DB_HOST:localhost}"
    port: "${DB_PORT:5432}"
    database: "${DB_NAME:requests_db}"
    schema: "${DB_SCHEMA:public}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:postgres123}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"
adapter:
  restconsumer:
    timeout: 5000
    url: "${ADAPTER_RESTCONSUMER_URL:http://localhost:8080}"
    paths:
      findByIdentificationNumber: "/api/v1/usuarios/{identificationNumber}"
      validateToken: "/auth/api/v1/validate/{jwt}"
      getAllUserInfoByEmail: "/api/v1/usuarios/email/{email}"
  sqs:
    manual-review:
      region: "${AWS_REGION:us-east-2}"
      queueUrl: "${SQS_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/058264169618/CrediYaQueue}"
    automatic-review:
      region: "${AWS_REGION:us-east-2}"
      queueUrl: "${SQS_AUTOMATIC_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/058264169618/debtAutomaticSQS}"
    accessKeyId: "${AWS_ACCESS_KEY_ID}"
    secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
routes:
  paths:
    request: "/api/v1/requests"
    getAllRequests: "/api/v1/requests"
    updateRequestStatus: "/api/v1/requests/{id}/status"
entrypoint:
  sqs:
    region: "${AWS_REGION:us-east-2}"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/058264169618/loanStatusAutomaticValidatorSQS"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
